backend:
  name: turbo-github
  turbo_site_id: 163e247b-645b-488b-82f3-30ab8836ecc3
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    sortable_fields:
      - "date"
      - "title"

    view_filters:
      - label: "草稿"
        field: "draft"
        pattern: true

    fields:
      - label: "标题"
        name: "title"
        widget: "string"

      - label: "发布日期"
        name: "date"
        widget: "datetime"

      - label: "摘要"
        name: "description"
        widget: "text"
        required: false
        hint: "用于首页简介和 SEO 描述"

      - label: "封面图"
        name: "cover"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - {label: "图片", name: "image", widget: "image", required: false}
          - {label: "图片说明", name: "alt", widget: "string", required: false}
          - {label: "图下注释", name: "caption", widget: "string", required: false}

      - label: "分类"
        name: "categories"
        widget: "list"
        required: false

      - label: "标签"
        name: "tags"
        widget: "list"
        required: false

      - label: "草稿"
        name: "draft"
        widget: "boolean"
        default: false

      - label: "显示目录"
        name: "ShowToc"
        widget: "boolean"
        default: true
        required: false

      - label: "排序权重（越小越靠前，留空按日期）"
        name: "weight"
        widget: "number"
        value_type: "int"
        min: 1
        required: false

      - label: "正文"
        name: "body"
        widget: "markdown"
